### ISSUE TITLE
[Question] - configuration for arduino Nano

### ISSUE THREAD

**Issue by ebroecker** [dergraaf/bootloader-can#1]
I am fighting with this code to get it running on an Arduino Nano.
As the nano is a atmega328p the only change I had to make to you code was to set  
`F_CPU = 16000000`

But this seems not to work yet. I am not sure if I have other issues at my side.
Maybe you have a hint for me.

[The crystal of the mcp2515 is 8Mhz]

Thanks,
Eduard

**Comment by dergraaf** [comment]
> [The crystal of the mcp2515 is 8Mhz]

The configuration is set up for a frequency of 16 MHz. You'll have to define new values for R_CNF1..3 for 8 MHz.

**Comment by ebroecker** [comment]
thanks for this hint!
I finally got it working.

For others who want to get this bootloader working on an arduino, maybe you could use this fork:
https://github.com/ma-go/AtmegaCanBootloader
